# Generated by Django 2.0.1 on 2018-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20180412_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='USA', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(default='NaN', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(default='NaN', max_length=20),
        ),
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(default=23),
        ),
    ]
